export default {
    "color": {
        "key": {
            "primary": "hsl(216, 98%, 52%)",
                "secondary": "hsl(223, 65%, 15%)",
                    "tertiary": "hsl(198, 76%, 52%)",
                        "neutral": "hsl(0, 0%, 54%)",
                            "neutralVariant": "hsl(0, 0%, 50%)",
                                "success": "hsl(152, 69%, 31%)",
                                    "error": "hsl(0, 68%, 50%)"
        },
        "palette": {
            "primary": {
                "0": "hsl(0, 0%, 0%)",
                    "10": "hsl(219, 100%, 14%)",
                        "20": "hsl(217, 100%, 22%)",
                            "30": "hsl(215, 100%, 31%)",
                                "40": "hsl(215, 100%, 41%)",
                                    "50": "hsl(216, 99%, 53%)",
                                        "60": "hsl(222, 100%, 67%)",
                                            "70": "hsl(223, 100%, 76%)",
                                                "80": "hsl(225, 100%, 85%)",
                                                    "87": "hsl(227, 100%, 90%)",
                                                        "90": "hsl(227, 100%, 93%)",
                                                            "92": "hsl(230, 100%, 94%)",
                                                                "94": "hsl(231, 100%, 96%)",
                                                                    "95": "hsl(233, 100%, 97%)",
                                                                        "96": "hsl(235, 100%, 97%)",
                                                                            "98": "hsl(257, 100%, 99%)",
                                                                                "99": "hsl(285, 100%, 99%)",
                                                                                    "100": "hsl(0, 0%, 100%)"
            },
            "secondary": {
                "0": "hsl(0, 0%, 0%)",
                    "10": "hsl(223, 69%, 14%)",
                        "20": "hsl(224, 42%, 23%)",
                            "30": "hsl(226, 30%, 32%)",
                                "40": "hsl(226, 24%, 42%)",
                                    "50": "hsl(226, 22%, 52%)",
                                        "60": "hsl(227, 28%, 62%)",
                                            "70": "hsl(226, 41%, 73%)",
                                                "80": "hsl(227, 69%, 84%)",
                                                    "87": "hsl(228, 100%, 91%)",
                                                        "90": "hsl(230, 100%, 93%)",
                                                            "92": "hsl(231, 100%, 95%)",
                                                                "94": "hsl(231, 100%, 96%)",
                                                                    "95": "hsl(233, 100%, 97%)",
                                                                        "96": "hsl(235, 100%, 97%)",
                                                                            "98": "hsl(257, 100%, 99%)",
                                                                                "99": "hsl(285, 100%, 99%)",
                                                                                    "100": "hsl(0, 0%, 100%)"
            },
            "tertiary": {
                "0": "hsl(0, 0%, 0%)",
                    "10": "hsl(199, 100%, 9%)",
                        "20": "hsl(198, 100%, 15%)",
                            "30": "hsl(197, 100%, 21%)",
                                "40": "hsl(196, 100%, 27%)",
                                    "50": "hsl(196, 100%, 34%)",
                                        "60": "hsl(196, 100%, 41%)",
                                            "70": "hsl(199, 85%, 59%)",
                                                "80": "hsl(202, 100%, 75%)",
                                                    "87": "hsl(204, 100%, 85%)",
                                                        "90": "hsl(204, 100%, 88%)",
                                                            "92": "hsl(205, 100%, 91%)",
                                                                "94": "hsl(205, 100%, 93%)",
                                                                    "95": "hsl(206, 100%, 95%)",
                                                                        "96": "hsl(207, 100%, 96%)",
                                                                            "98": "hsl(210, 100%, 98%)",
                                                                                "99": "hsl(225, 100%, 99%)",
                                                                                    "100": "hsl(0, 0%, 100%)"
            },
            "neutral": {
                "0": "hsl(0, 0%, 0%)",
                    "10": "hsl(180, 2%, 11%)",
                        "20": "hsl(240, 1%, 19%)",
                            "30": "hsl(180, 1%, 28%)",
                                "40": "hsl(0, 0%, 37%)",
                                    "50": "hsl(0, 0%, 47%)",
                                        "60": "hsl(0, 0%, 57%)",
                                            "70": "hsl(0, 0%, 67%)",
                                                "80": "hsl(0, 1%, 78%)",
                                                    "87": "hsl(30, 3%, 85%)",
                                                        "90": "hsl(0, 2%, 89%)",
                                                            "92": "hsl(0, 2%, 91%)",
                                                                "94": "hsl(0, 6%, 93%)",
                                                                    "95": "hsl(0, 7%, 95%)",
                                                                        "96": "hsl(0, 9%, 96%)",
                                                                            "98": "hsl(0, 9%, 98%)",
                                                                                "99": "hsl(0, 20%, 99%)",
                                                                                    "100": "hsl(0, 0%, 100%)"
            },
            "neutralVariant": {
                "0": "hsl(0, 0%, 0%)",
                    "10": "hsl(180, 2%, 11%)",
                        "20": "hsl(240, 1%, 19%)",
                            "30": "hsl(180, 1%, 28%)",
                                "40": "hsl(0, 0%, 37%)",
                                    "50": "hsl(0, 0%, 47%)",
                                        "60": "hsl(60, 0%, 57%)",
                                            "70": "hsl(0, 0%, 67%)",
                                                "80": "hsl(0, 1%, 78%)",
                                                    "87": "hsl(30, 3%, 85%)",
                                                        "90": "hsl(0, 2%, 89%)",
                                                            "92": "hsl(0, 2%, 91%)",
                                                                "94": "hsl(0, 6%, 93%)",
                                                                    "95": "hsl(0, 7%, 95%)",
                                                                        "96": "hsl(0, 9%, 96%)",
                                                                            "98": "hsl(0, 9%, 98%)",
                                                                                "99": "hsl(30, 33%, 99%)",
                                                                                    "100": "hsl(0, 0%, 100%)"
            },
            "success": {
                "0": "hsl(0, 0%, 0%)",
                    "10": "hsl(149, 100%, 6%)",
                        "20": "hsl(153, 100%, 11%)",
                            "30": "hsl(154, 100%, 16%)",
                                "40": "hsl(155, 100%, 21%)",
                                    "50": "hsl(152, 66%, 32%)",
                                        "60": "hsl(148, 45%, 44%)",
                                            "70": "hsl(145, 43%, 55%)",
                                                "80": "hsl(144, 57%, 66%)",
                                                    "87": "hsl(143, 74%, 74%)",
                                                        "90": "hsl(143, 86%, 77%)",
                                                            "92": "hsl(143, 96%, 80%)",
                                                                "94": "hsl(141, 100%, 85%)",
                                                                    "95": "hsl(138, 100%, 88%)",
                                                                        "96": "hsl(136, 100%, 91%)",
                                                                            "98": "hsl(128, 100%, 96%)",
                                                                                "99": "hsl(115, 100%, 98%)",
                                                                                    "100": "hsl(0, 0%, 100%)"
            },
            "error": {
                "0": "hsl(0, 0%, 0%)",
                    "10": "hsl(358, 100%, 13%)",
                        "20": "hsl(357, 100%, 21%)",
                            "30": "hsl(355, 100%, 29%)",
                                "40": "hsl(357, 83%, 40%)",
                                    "50": "hsl(1, 75%, 53%)",
                                        "60": "hsl(3, 100%, 65%)",
                                            "70": "hsl(5, 100%, 75%)",
                                                "80": "hsl(6, 100%, 84%)",
                                                    "87": "hsl(7, 100%, 89%)",
                                                        "90": "hsl(6, 100%, 92%)",
                                                            "92": "hsl(7, 100%, 94%)",
                                                                "94": "hsl(7, 100%, 95%)",
                                                                    "95": "hsl(9, 100%, 96%)",
                                                                        "96": "hsl(7, 100%, 97%)",
                                                                            "98": "hsl(7, 100%, 98%)",
                                                                                "99": "hsl(300, 100%, 99%)",
                                                                                    "100": "hsl(0, 0%, 100%)"
            }
        },
        "role": {
            "light": {
                "primary": "{color.key.primary}",
                    "onPrimary": "{color.palette.primary.100}",
                        "primaryContainer": "{color.palette.primary.80}",
                            "onPrimaryContainer": "{color.palette.primary.30}",
                                "secondary": "{color.palette.secondary.40}",
                                    "onSecondary": "{color.palette.secondary.100}",
                                        "secondaryContainer": "{color.palette.secondary.80}",
                                            "onSecondaryContainer": "{color.palette.secondary.30}",
                                                "tertiary": "{color.palette.tertiary.40}",
                                                    "onTertiary": "{color.palette.tertiary.100}",
                                                        "tertiaryContainer": "{color.palette.tertiary.80}",
                                                            "onTertiaryContainer": "{color.palette.tertiary.30}",
                                                                "error": "{color.palette.error.40}",
                                                                    "onError": "{color.palette.error.100}",
                                                                        "errorContainer": "{color.palette.error.80}",
                                                                            "onErrorContainer": "{color.palette.error.30}",
                                                                                "background": "{color.palette.neutral.98}",
                                                                                    "onBackground": "{color.palette.neutral.10}",
                                                                                        "surface": "{color.palette.neutral.98}",
                                                                                            "onSurface": "{color.palette.neutral.10}",
                                                                                                "surfaceVariant": "{color.palette.neutralVariant.90}",
                                                                                                    "onSurfaceVariant": "{color.palette.neutralVariant.30}",
                                                                                                        "outline": "{color.palette.neutralVariant.50}",
                                                                                                            "outlineVariant": "{color.palette.neutralVariant.80}",
                                                                                                                "inverseSurface": "{color.palette.neutral.20}",
                                                                                                                    "inverseOnSurface": "{color.palette.neutral.95}",
                                                                                                                        "inversePrimary": "{color.palette.primary.80}",
                                                                                                                            "surfaceDim": "{color.palette.neutral.87}",
                                                                                                                                "surfaceBright": "{color.palette.neutral.98}",
                                                                                                                                    "surfaceContainerLowest": "{color.palette.neutral.100}",
                                                                                                                                        "surfaceContainerLow": "{color.palette.neutral.96}",
                                                                                                                                            "surfaceContainer": "{color.palette.neutral.94}",
                                                                                                                                                "surfaceContainerHigh": "{color.palette.neutral.92}",
                                                                                                                                                    "surfaceContainerHighest": "{color.palette.neutral.90}"
            },
            "dark": {
                "primary": "{color.key.primary}",
                    "onPrimary": "{color.palette.primary.20}",
                        "primaryContainer": "{color.palette.primary.30}",
                            "onPrimaryContainer": "{color.palette.primary.90}",
                                "secondary": "{color.palette.secondary.80}",
                                    "onSecondary": "{color.palette.secondary.20}",
                                        "secondaryContainer": "{color.palette.secondary.30}",
                                            "onSecondaryContainer": "{color.palette.secondary.90}",
                                                "tertiary": "{color.palette.tertiary.80}",
                                                    "onTertiary": "{color.palette.tertiary.20}",
                                                        "tertiaryContainer": "{color.palette.tertiary.30}",
                                                            "onTertiaryContainer": "{color.palette.tertiary.90}",
                                                                "error": "{color.palette.error.80}",
                                                                    "onError": "{color.palette.error.20}",
                                                                        "errorContainer": "{color.palette.error.30}",
                                                                            "onErrorContainer": "{color.palette.error.90}",
                                                                                "background": "{color.palette.neutral.6}",
                                                                                    "onBackground": "{color.palette.neutral.90}",
                                                                                        "surface": "{color.palette.neutral.6}",
                                                                                            "onSurface": "{color.palette.neutral.90}",
                                                                                                "surfaceVariant": "{color.palette.neutralVariant.30}",
                                                                                                    "onSurfaceVariant": "{color.palette.neutralVariant.80}",
                                                                                                        "outline": "{color.palette.neutralVariant.60}",
                                                                                                            "outlineVariant": "{color.palette.neutralVariant.30}",
                                                                                                                "inverseSurface": "{color.palette.neutral.90}",
                                                                                                                    "inverseOnSurface": "{color.palette.neutral.20}",
                                                                                                                        "inversePrimary": "{color.palette.primary.40}",
                                                                                                                            "surfaceDim": "{color.palette.neutral.6}",
                                                                                                                                "surfaceBright": "{color.palette.neutral.24}",
                                                                                                                                    "surfaceContainerLowest": "{color.palette.neutral.4}",
                                                                                                                                        "surfaceContainerLow": "{color.palette.neutral.10}",
                                                                                                                                            "surfaceContainer": "{color.palette.neutral.12}",
                                                                                                                                                "surfaceContainerHigh": "{color.palette.neutral.17}",
                                                                                                                                                    "surfaceContainerHighest": "{color.palette.neutral.22}"
            }
        }
    }
}